### ISSUE TITLE
player's inventory

### ISSUE THREAD

**Issue by oxXLucasXxo** [oryboot/NSI#17]
Si vous acceptez je peux m'occuper de créer un inventaire (pour les items qu'il peut ramasser etc.). Ca vous va si je mets qu'il y a trois types d'items? tool, potion, weapon

**Comment by oryboot** [comment]
no weapons cus the game isnt based on fighting with weapons but what do you mean by "tools" ? that could be interesting to build an ingame player inventory but i don't really see wym by tools

**Comment by oxXLucasXxo** [comment]
imagine a secret passage in a cave that brings you to another cave but without any light so everything is dark. you'd need a torch (8nov) to light up the place and see what's going on. i worked with my best friend on the game have a look: 
[RPG_Game_Development_Summary_Updated.pdf](https://github.com/user-attachments/files/17880226/RPG_Game_Development_Summary_Updated.pdf)

**Comment by oxXLucasXxo** [comment]
for weapons even if you don't aim at your enemy you can use it (varying damage depending on weapon type)

**Comment by oxXLucasXxo** [comment]
also can you stack potions (like in minecraft)?
i'll make the inventory space-limited (2 potions, 2 weapons, 2 tools)
again for tools it can be a pickaxe it can be used in a quest given by an npc

**Comment by oxXLucasXxo** [comment]
isn't it too much?
and also maybe the player slows down proportionally to the total weight of the items he has in its inventory...

**Comment by oryboot** [comment]
nah too complex shit over here lol, yeah youre right it might be a bit too much, lower it as you think its the most balanced

**Comment by oxXLucasXxo** [comment]
try to merge (2 pull requests)
pay attention i modified a folder name so it should complicate the task...

**Comment by oryboot** [comment]
other pull request has got conflicts in it, what should i do ?
