### ISSUE TITLE
About the recent update of menu

### ISSUE THREAD

**Issue by oxXLucasXxo** [oryboot/NSI#34]
@stevemaronix 
some_variable.lower()
will change the value of the variable

lower(some_variable) won't but will take the lowered variable so you can let it as it was 👍

**Comment by stevemaronix** [comment]
Bah je sais pas j'avais essayé d'y ça marchait pas. Après j'ai modifié et ça marchait. Après ça dépend peut être de la version de Python.

**Comment by oxXLucasXxo** [comment]
Bizarre de mon côté ça fonctionnait. On laisse comme ca je reverrai après...

**Comment by stevemaronix** [comment]
Et même tout à l'heure en NSI sur les PC du lycée, les f-string n'étaient pas supportés. Donc c'est pour ça, ça dépend de la version de Python mais au pire c'est pas grave.
